# Generated by Django 5.1.4 on 2025-02-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='FALSE', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='FALSE', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='FALSE'),
        ),
    ]
