# Generated by Django 5.1.4 on 2025-02-10 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
