# Generated by Django 5.1.4 on 2025-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='descrpiton',
            field=models.TextField(blank=True, null=True),
        ),
    ]
