# Generated by Django 5.1.4 on 2025-03-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_role_descrpiton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
